version: '3'

services:
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    ports:
      - "3307:3306"
    networks:
      - my_network
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d


  backend:
    image: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops
      SPRING_DATASOURCE_USERNAME : root
      SPRING_DATASOURCE_PASSWORD : root

    depends_on:
      - db
    networks:
      - my_network



networks:
  my_network:
    driver: bridge